[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["E", "F", "Q", "I"]
fixable = ["ALL"]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.basedpyright]
typeCheckingMode = "basic"
